#
# Hardware settings for my Laptop
#
# flake.nix
#  └─ ./hosts
#      └─ ./desktop
#          └─ hardware-configuration.nix *
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#

{ config, lib, modulesPath, ... }:

{

    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

      boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" =
        { device = "/dev/disk/by-uuid/ebb032f5-7f11-49af-a476-217d0af8fb49";
          fsType = "ext4";
        };

      fileSystems."/run/media/luan/win" =
        { device = "/dev/disk/by-uuid/1C7A3F5A7A3F303E";
          fsType = "ntfs";
        };

      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/5C91-AE10";
          fsType = "vfat";
          options = [ "fmask=0077" "dmask=0077" ];
        };

      swapDevices =
        [ { device = "/dev/disk/by-uuid/1fbba748-00f6-48aa-b564-040114b4a7dd"; }
        ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking = {
    # useDHCP = false;                            # Deprecated
    hostName = "laptop";
    #networkmanager.enable = true;
    # enableIPv6 = false;
    # interfaces = {
    #   enp2s0 = {                                # Change to correct network driver
    useDHCP = lib.mkDefault true;                       # Disabled because fixed ip
    #     ipv4.addresses = [ {                    # Ip settings: *.0.50 for main machine
    #       address = "192.168.0.50";
    #       prefixLength = 24;
    #     } ];
    #   };
      #wlp2s0.useDHCP = true;                   # Wireless card
    # };
    # defaultGateway = "192.168.0.1";
    # nameservers = [ "192.168.0.4" "1.1.1.1"];            # Pi-Hole DNS
    #nameservers = [ "1.1.1.1" "1.0.0.1" ];     # Cloudflare (when Pi-Hole is down)
  };
}
